### ISSUE TITLE
Tag `seo`

### ISSUE THREAD

**Issue by Corotyest** [Bilal2453/cayman-docs#1]
I doing testes while deleting one, and another.

When I noticed the theme is going wrong, how do I explain it; basically GitHub say this: "Your site is having problems building: The tag seo on line 16 in /_layouts/default.html is not a recognized Liquid tag"

Is this normal?

**Comment by Bilal2453** [comment]
When exactly does it say that? how are you trying to build it?

**Comment by Corotyest** [comment]
![image](https://user-images.githubusercontent.com/74837790/141828196-feaacbec-3a50-4b4e-92d8-dcbbcf2fc641.png)

# Steps:

# Doing _config.yml (adding theme)
![image](https://user-images.githubusercontent.com/74837790/141828273-130b021f-8b56-4a89-b65f-834ee8938257.png)

# Changing README (this not take effect for the issue in tag)
![image](https://user-images.githubusercontent.com/74837790/141828286-1d24e4ee-5cdf-4c2b-951a-30ca24d3cc40.png)

**Comment by Bilal2453** [comment]
This happens because you are not following the expected structure. For an example of a functional build with this theme take a look at this [repo](https://github.com/bilal2453/coro-docs/), notice [_config.yaml](https://github.com/Bilal2453/coro-docs/blob/master/_config.yml), if you go to the docs folder, notice how each [markdown](https://raw.githubusercontent.com/Bilal2453/coro-docs/master/docs/coro-channel.md) is written. The structure and _config.yaml needs to be something similar, otherwise I don't seem to be able to replicate your issue.

**Comment by Corotyest** [comment]
That makes sense, well I made a semi-copy of the repository ([this](https://github.com/Corotyest/corotyest.github.io)) and it turned out that not even GitHub makes the confirmation, for half an hour. 

Ah and the Issues from GitHub persist, so what proceed from here.

**Comment by Corotyest** [comment]
I mean doesn't even throw an error.

**Comment by Bilal2453** [comment]
Hm, if you go to your [Repo's Pages Settings](https://github.com/Corotyest/corotyest.github.io/settings/pages), what theme does it show you are using? It should be something similar to this below
![image](https://user-images.githubusercontent.com/38175840/142185447-978f3e7d-9a9d-4f5c-a4e3-8a8b4f171b79.png)

**Comment by Corotyest** [comment]
Yes, it is using the Cayman theme. What more?
![image](https://user-images.githubusercontent.com/74837790/142243791-e1f642c7-c7ce-44f4-bf24-82bb04531662.png)

**Comment by Corotyest** [comment]
May I amplify the image

**Comment by Bilal2453** [comment]
Hm, honestly not quite sure what's happening there, also sorry for the late reply, I was quite busy.  I will have to look into it eventually, although as of now the main goal of this was for a personal use (the coro-docs thing) and it works there, I do eventually plan onto updating that, so once I do I will look into this.

**Comment by Corotyest** [comment]
Thank you, and it's no problem, I use it for two reasons: Looks cool and support. I can wait for it take your time.

**Comment by Corotyest** [comment]
Hi, it has been a while since the last comment and now I have this log for your understanding.
[logs_6.zip](https://github.com/Bilal2453/cayman-docs/files/9914212/logs_6.zip)

**Comment by Bilal2453** [comment]
Hey could you please retry this?  I just tried [it here](https://github.com/Bilal2453/test-cayman-docs) and it worked just fine!  (You can visit the test [website here](https://bilal2453.github.io/test-cayman-docs/))

The steps for using this are simple:

1. Create a new repo and enable Pages.
2. Create a `_config.yml` file in the branch of the Pages (this is selected in settings, by default IT IS NOT the main/master branch!)
3. Add a `remote_theme: Bilal2453/cayman-docs` property, make sure that there is no `theme` property!

Please re-open this issue if it persists.
